---
- name: install python-dateutil
  apt: name={{ item }} state=present 
  with_items:
    - python-dateutil
    - git
  sudo: yes
- name: clone s3tools repository
  git: repo=http://github.com/s3tools/s3cmd.git dest=/usr/local/src/s3cmd update=no
  sudo: yes
- name: linking s3cmd to /usr/local/bin
  file: src=/usr/local/src/s3cmd/s3cmd path=/usr/local/bin/s3cmd state=link
  sudo: yes
- name: writing s3cmd configuration file to home directory
  template:
    src: s3cfg.j2
    dest: /home/{{ ansible_ssh_user }}/.s3cfg
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0644

